Using multiuser mode by default. Automatic checking of filesystems added to startup script.

diff --git a/etc/rc b/etc/rc
--- a/etc/rc
+++ b/etc/rc
@@ -3,13 +3,45 @@ HOME=/; export HOME
 PATH=/bin:/sbin; export PATH
 exec >/dev/console 2>&1
 
-if test "$1" != 'autoboot'; then
+if test "$1" != "autoboot"; then
     # On exit from single-user mode - halt the processor.
     echo
-    reboot -l -h
+    echo "--- Exit single-user mode"
+    #reboot -l -h
+    exit 0
 fi
 
-hostname 'pic32'
+#
+# Entering multiuser mode.
+#
+echo "--- Check filesystems"
+
+# This will *only* work if fsck can do your root file system
+# without a temporary file, and if the root file system is
+# checked alone in a pass by itself -- be careful!  This can
+# *seriously* mess you up.
+fsck -p
+case $? in
+0)
+    echo "--- Filesystems are clean" ;;
+2)
+    echo "--- Critical errors detected, repair manually"
+    exit 1 ;;
+4)
+    echo "--- Root filesystem repaired, rebooting..."
+    reboot -n ;;
+8)
+    echo "--- Filesystem check failed... help!"
+    exit 1 ;;
+12)
+    echo "--- Check interrupted"
+    exit 1 ;;
+*)
+    echo "--- Unknown error in fsck"
+    exit 1 ;;
+esac
+
+hostname "pic32"
 
 #
 # First umount everything in case the system is going back into multiuser
@@ -17,6 +49,7 @@ hostname 'pic32'
 # except the root filesystem and umount ignores attempts to unmount /.
 #
 umount -a
+
 #
 # Now mount everything mentioned in /etc/fstab *except* filesystems with the
 # 'na' (noauto) option.
@@ -25,11 +58,9 @@ mount -a
 
 rm -f /etc/nologin
 
-echo -n standard daemons:
-update && echo -n ' update'
-echo '.'
+echo -n "Standard daemons:"
+update && echo -n "update"
+echo
 
 #/etc/rc.local
-
-date
 exit 0
